### ISSUE TITLE
Add recognition for: `/** @type {{[key: string]: string}} */`

### ISSUE THREAD

**Issue by thernstig** [jsdoc-type-pratt-parser/jsdoc-type-pratt-parser#101]
## Expected behavior

This should be valid (it is called an index signature https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures).
```js
/** @type {{[key: string]: string}} */
const obj = {};
obj.a = 'foo';
obj.b = 5;
```

## Actual behavior
It is not as it gives the error `Syntax error in type: {[key: string]: string}`

## ESLint Config

```json
  "settings": {
    "jsdoc": {
      "mode": "typescript",
    }
  }
```

## Environment

- Node version: v14.17.6
- ESLint version: v7.32.0
- `eslint-plugin-jsdoc` version: 36.1.0

**Comment by jaydenseric** [comment]
Also, support `()` after the square brackets; here is an example for a `FileList` polyfill I'm using in some tests:

```js
/**
 * @param {Array<File>} files Files.
 * @this {{
 *   #files: Array<File>,
 *   [index: number]: File,
 *   [Symbol.iterator](): IterableIterator<File>,
 *   length: number
 * }}
 */
```

**Comment by simonseyock** [comment]
@jaydenseric this is an unrelated issue. I think this is a `computed declaration` as mentioned in https://www.typescriptlang.org/docs/handbook/symbols.html. I will first solve the index signature.

**Comment by thernstig** [comment]
@brettz9 is this an easy one to fix?

**Comment by brettz9** [comment]
We are using this project in `eslint-plugin-jsdoc`, but its codebase is not something *deeply* familiar to me nor do I have the inclination to work on this now. The project does have instructions on how to contribute a new rule if you would like.

**Comment by simonseyock** [comment]
@thernstig This sadly is not one of the easier issues, as the object parsing is very complex. Pratt-parsing inherently does not support context switching which is needed for this functionality (inside of an object tokens have other meanings than outside). So the way to do this is to extend the normal pratt parsing by some context-switching capabilities. I was working on this, but got sidetracked. Maybe pratt-parsing is not the best for more complex context-sensitive parsing ... but it should be possible

**Comment by thernstig** [comment]
@simonseyock I might be entirely out on a limb here, but is there no way to have the grammer `typescript` actually use https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API or something similar? Or "tsc" directly or what not?

**Comment by simonseyock** [comment]
@thernstig It would be best if we could use that. This parser is mainly recreating stuff that already exists in `tsc` and we will allways have to play catch up. Also the very advanced features are very hard if not impossible to implement with a parser like this. (It actually can only parse deterministic context-free grammars and I am almost sure that the typescript type system is more complex - with conditional types and everything). But I don't know exactly if that works as there are some oddities and quirks about using this in an eslint plugin.

Also I don't know how good the actual documentation is. I think I looked into it at some point, but did not find the ressources I would need.

It is for sure worth looking into.
