### ISSUE TITLE
Parsing a TypeScript type predicate results in a syntax error

### ISSUE THREAD

**Issue by jaydenseric** [jsdoc-type-pratt-parser/jsdoc-type-pratt-parser#108]
**Describe the issue**

Parsing a [TypeScript type predicate](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) results in a syntax error.

**To Reproduce**

Here is a realistic example with a JSDoc `@returns` type:

```js
/**
 * Checks if an event is a {@linkcode CustomEvent}.
 * @param {Event} event Event.
 * @returns {event is CustomEvent} Is it a {@linkcode CustomEvent}.
 */
function isCustomEvent(event) {
  return event instanceof CustomEvent;
}
```

Try parsing the `@returns` type in the [tester](https://jsdoc-type-pratt-parser.github.io/jsdoc-type-pratt-parser/) with the `TypeScript` type syntax selected to see the bug:

```
event is CustomEvent
```

Result:

```
Error: The parsing ended early. The next token was: 'Identifier' with value 'is'
```

**Expected behavior**

Parsing a [TypeScript type predicate](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) shouldn't result in a syntax error; I'm not sure what the desirable AST is.

**Additional context**

Due to this bug, the ESLint [`jsdoc/valid-types`](https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-valid-types) rule has a syntax error when using a [TypeScript type predicate](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) within a JSDoc `@returns` type.

**Comment by simonseyock** [comment]
Thanks for this report. Predicates are currently not supported. I will try to add them soon.
