### ISSUE TITLE
Error while parsing arrow function definitions using object literal syntax

### ISSUE THREAD

**Issue by macku** [jsdoc-type-pratt-parser/jsdoc-type-pratt-parser#119]
**Describe the issue**
Hi, I've found some problems with parsing type definitions while I was using the [`eslint-plugin-jsdoc`](https://www.npmjs.com/package/eslint-plugin-jsdoc) project:

**To Reproduce**
With TypeScript, you can use JSDoc annotation to define types inside pure JavaScript files. You can use JSDoc to define complex object literal types when using, e.g. `@type` keyword.

https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#type

While the parser works fine with a simple types, it has problems when parsing arrow functions definitions:

```js
const { parse } = require('jsdoc-type-pratt-parser');

try {
  parse('React.FC<{ onDrag: () => void, onDrop: () => void }>', 'typescript');
  console.log('parsed two arrow functions');
} catch (e) {
  console.log('error while parsing two arrow functions');
}


try {
  parse('React.FC<{ onDrag: () => void, isDragging: boolean }>', 'typescript');
  console.log('parsed arrow function and boolean');
} catch (e) {
  console.log('error while parsing boolean and arrow function');
}

try {
  parse('React.FC<{ isDragging: boolean, onDrag: () => void }>', 'typescript');
  console.log('parsed boolean and arrow function');
} catch (e) {
  console.log('error while parsing boolean and arrow function');
}
```

Running this code will result in:
```
error while parsing two arrow functions
error while parsing boolean and arrow function
parsed boolean and arrow function
```

**Expected behavior**
The arrow function expression should be parsed without an error.

**Additional context**

**Comment by macku** [comment]
It's worth mentioning that this is not related to using generic types since stripping the `React.FC<>` from the definitions will result in the same errors:

```js
const { parse } = require('jsdoc-type-pratt-parser');

try {
  parse('{ onDrag: () => void, onDrop: () => void }', 'typescript');
  console.log('parsed two arrow functions');
} catch (e) {
  console.log('error while parsing two arrow functions');
}


try {
  parse('{ onDrag: () => void, isDragging: boolean }', 'typescript');
  console.log('parsed arrow function and boolean');
} catch (e) {
  console.log('error while parsing boolean and arrow function');
}

try {
  parse('{ isDragging: boolean, onDrag: () => void }', 'typescript');
  console.log('parsed boolean and arrow function');
} catch (e) {
  console.log('error while parsing boolean and arrow function');
}
```

**Comment by simonseyock** [comment]
Thanks for this report! This is most likely a precedence error. Probably I can fix this easily.

**Comment by simonseyock** [comment]
FYI: The paresr tester is working again, so you can test type strings here again: https://jsdoc-type-pratt-parser.github.io/jsdoc-type-pratt-parser/

**Comment by brettz9** [comment]
@simonseyock : FWIW, I'm getting a page not found

**Comment by simonseyock** [comment]
ah thanks, then there is still something broken with the deploy workflow. have to check that

**Comment by simonseyock** [comment]
@brettz9 seems to work again

**Comment by brettz9** [comment]
Looking good, thanks!
