### ISSUE TITLE
Syntax error in type: `/** @type {() => Object} */`

### ISSUE THREAD

**Issue by snebjorn** [jsdoc-type-pratt-parser/jsdoc-type-pratt-parser#130]
**Describe the issue**
I'm getting this error `Syntax error in type: () => Object` on the following

```js
/** @type {() => Object} */
const foo = () => new Object();
```
![image](https://user-images.githubusercontent.com/1266245/155892711-1a3949af-ca59-4760-9967-cf0eb2f77320.png)

**To Reproduce**
Code:
```js
/** @type {() => Object} */
const foo = () => new Object();
```

Parser output - not exactly sure what to do here but I made it output this:
```json
{
  "type": "JsdocTypeFunction",
  "parameters": [],
  "arrow": true,
  "parenthesis": true,
  "returnType": {
    "type": "JsdocTypeName",
    "value": "Object"
  }
}
```

**Expected behavior**
I'd expect a lambda function to be a valid syntax for a type.

**Comment by simonseyock** [comment]
Hello @snebjorn, thanks for reporting this! It seems the Parser handles this just fine - see parser output is correct. So there is either a problem in the [eslint plugin](https://github.com/gajus/eslint-plugin-jsdoc) or you are using a wrong mode `jsdoc` and (google-)`closure` can't handle arrow functions.

**Comment by snebjorn** [comment]
changing the mode to typescript did the trick. Sorry for the bother
