### ISSUE TITLE
Line break separators

### ISSUE THREAD

**Issue by brettz9** [jsdoc-type-pratt-parser/jsdoc-type-pratt-parser#135]
**Describe the issue**

The parser tester at least does not accept line breaks as a sufficient separator despite TypeScript's parser accepting them as such.

**To Reproduce**
Please provide failing expressions and the actual parser output. You can use https://jsdoc-type-pratt-parser.github.io/jsdoc-type-pratt-parser/ for this.

1. Supply this type to the tester:

```
{
  range: boolean
  loc: boolean
}
```
2. See the result: `Error: Unterminated record type. Missing '}'`

**Expected behavior**
Please provide the expected parser output for the expression if you can.

```json
{
  "type": "JsdocTypeObject",
  "meta": {
    "separator": lineBreak????
  },
  "elements": [
    {
      "type": "JsdocTypeKeyValue",
      "key": "range",
      "right": {
        "type": "JsdocTypeName",
        "value": "boolean"
      },
      "optional": false,
      "readonly": false,
      "meta": {
        "hasLeftSideExpression": false
      }
    },
    {
      "type": "JsdocTypeKeyValue",
      "key": "loc",
      "right": {
        "type": "JsdocTypeName",
        "value": "boolean"
      },
      "optional": false,
      "readonly": false,
      "meta": {
        "hasLeftSideExpression": false
      }
    }
  ]
}
```

**Additional context**

**Comment by simonseyock** [comment]
Thanks for the report. For this to work we will need a new Token `'LineBreak'` in the lexer. Before it was just discarding any whitespace before and after each token. No I will add the new Token if a line break exists. The only issue might be that now other parsing fails where linebreaks where allowed before. Maybe I can add a kind of backtracking where it first tries to parse with the linebreak token and then without if it detects one.

**Comment by simonseyock** [comment]
I have a solution that works without adding another token type. The only problem that exists is the stringification of a type as at the moment we don't store any whitespace in the AST. The given example would be stringified as `{range: boolean; loc: boolean}`. I don't know if you use that, but I think this is still a good first step.

**Comment by simonseyock** [comment]
ok. I was wondering about this. At the moment the first separator is returned, while other separators are respected but not returned.
