### ISSUE TITLE
Accessing array returned by utility type Parameters results in error

### ISSUE THREAD

**Issue by lieser** [jsdoc-type-pratt-parser/jsdoc-type-pratt-parser#141]
**Describe the issue**

The utility type [`Parameters`](https://www.typescriptlang.org/docs/handbook/utility-types.html#parameterstype) returns an array. Accessing that array using square brackets results in a parsing error.

**To Reproduce**

Input: `Parameters<testFunc>[0]`
Output by https://jsdoc-type-pratt-parser.github.io/jsdoc-type-pratt-parser/:
```
Error: The parsing ended early. The next token was: '[' with value '['
```

**Expected behavior**

Input should be accepted as a valid type.

**Additional context**

Note that Visual Studio Code supports this for JSDoc types.

Use case:
```js
/**
 * @param {string} string
 * @param {number} number
 * @returns {boolean}
 */
function testFunc(string, number) {
  return true;
}

// This currently fails:
// eslint(jsdoc/valid-types): Syntax error in type: Parameters<test>[0]
/** @type {Parameters<testFunc>[0]} */
const x = "foo";
```

**Comment by susnux** [comment]
Same with something like this:

```js
{
	 /**
	 * @type {import('focus-trap').Options['setReturnFocus']}
	 */
	setReturnFocus: ...
}
```

**Comment by MattIPv4** [comment]
👋 Also running into this.

I notice that `[ string, number ][0]` and `Parameters<(a: string, b: number) => void>[0]` both produce the `Error: The parsing ended early. The next token was: '[' with value '['` error.

The actual case I was using that ran into this (`Parameters<import('playwright-core').Page["getByRole"]>[0]`) produces a different parser error: `Error: Unterminated generic parameter list`.

All of these work in VSCode with their built-in JSDoc parsing.
