### ISSUE TITLE
Support TypeScript assertion function return types

### ISSUE THREAD

**Issue by jaydenseric** [jsdoc-type-pratt-parser/jsdoc-type-pratt-parser#162]
**Describe the issue**
A clear and concise description of what the issue is.

TypeScript assertion function return types result in a parse error.

**To Reproduce**

Please provide failing expressions and the actual parser output. You can use https://jsdoc-type-pratt-parser.github.io/jsdoc-type-pratt-parser/ for this.

```
asserts x is string
```

Which mode was used:
* [ ] `jsdoc`
* [ ] `closure`
* [x] `typescript`

(Please be aware that issues with `jsdoc` and `closure` modes probably won't get addressed because of lack of time)

**Expected behavior**
Please provide the expected parser output for the expression if you can.

I'm not sure what the exact parser output should be, as long as it's somehow supported for this situation and doesn't error.

In which modes would you expect the parser to accept the failing expression:
* [ ] `jsdoc`
* [ ] `closure`
* [x] `typescript`

**Additional context**

@brettz9 this appears to causing an ESLint rule [`jsdoc/valid-types`](https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-valid-types) error `Syntax error in type` for `@returns` type for a TypeScript assertion function:

<img width="622" alt="Screenshot 2023-05-07 at 3 32 35 pm" src="https://user-images.githubusercontent.com/1754873/236659631-419a4106-16bf-4a13-b6b4-014b41cba33a.png">

In the past support for TypeScript type predicates was added:

https://github.com/jsdoc-type-pratt-parser/jsdoc-type-pratt-parser/issues/108

But, they are different to an assertion function return type that starts with `asserts `, see:

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions

**Comment by unicornware** [comment]
looking for this support as well. 

i use my comments to build doc sites, so writing `void` or `x is string` is not ideal.
