### ISSUE TITLE
Add support for `@import`

### ISSUE THREAD

**Issue by Arkellys** [jsdoc-type-pratt-parser/jsdoc-type-pratt-parser#165]
Typescript 5.5 introduces the tag [`@import`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/#type-imports-in-jsdoc), which allows importing types (or other stuff) within JSDoc:

```js
/** @import { SomeType } from "some-module" */
```

Using named imports as the example above currently gives a `Syntax error in type` error, but works otherwise.

Would it be possible to add support for this new syntax?

**Comment by Arkellys** [comment]
Oh, I assumed I should create the issue here since the error is reported by the [`jsdoc/valid-types`](https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/valid-types.md#repos-sticky-header) rule, and that according to the docs valid types are determined by this parser.

Here is a way to reproduce the issue:

**types.js**
```js
/** @typedef {string} TestOne */
/** @typedef {string} TestTwo */
```

**other.js**
```js
/**
 * @import { TestOne, TestTwo } from "./types"  🡒  Syntax error in type: TestOne, TestTwo eslint(jsdoc/valid-types)
 * @import { TestOne } from "./types"  🡒  The type 'TestOne' is undefined. eslint(jsdoc/no-undefined-types)
 * @import * as Types from "./types"  🡒  No error
 */

// And regardless of the import used: 

/** 
 * @typedef {TestOne} Test  🡒  The type 'TestOne' is undefined. eslint(jsdoc/no-undefined-types)
 */ 
```

This is with `mode: "typescript"`, full config available [here](https://github.com/Arkellys/eslint-config-arklint/blob/main/extensions/jsdoc.js).

I will need to create an issue on  `eslint-plugin-jsdoc` repo anyway since I suppose the `no-undefined-types` errors are not related to the parser. I would be happy to get confirmation whether the `valid-types` error is from the parser.

**Comment by brettz9** [comment]
`valid-types` in this case is not due to the parser--it's part of `eslint-plugin-jsdoc`. Please file these details on `eslint-plugin-jsdoc`. Thanks!

**Comment by Arkellys** [comment]
All right, thanks for checking!
