### ISSUE TITLE
Support square brackets

### ISSUE THREAD

**Issue by Yash-Singh1** [jsdoc-type-pratt-parser/jsdoc-type-pratt-parser#95]
**Input**

```js
abc["abc"]
```

**Expected**

Something similar to this, with a few property changes for square brackets.

```js
{
  "type": "JsdocTypeNamePath",
  "left": {
    "type": "JsdocTypeName",
    "value": "abc"
  },
  "right": {
    "type": "JsdocTypeProperty",
    "value": "abc"
  },
  "pathType": "property"
}
```

**Actual**

```console
Error: The parsing ended early. The next token was: '[' with value '['
```

**More**

Visual Studio Code supports the square bracket syntax for JSDoc types.

**Comment by jaydenseric** [comment]
It's necessary for using TypeScript and JSDoc like this:

```js
/** @type {RequestInit["signal"]} */
let signal;
```

<img width="464" alt="Screen Shot 2021-12-29 at 11 18 32 pm" src="https://user-images.githubusercontent.com/1754873/147661389-6c857a0b-aa2b-48b7-af96-8b05606a3775.png">
